Repository ethyca/fides, pull requests merged in 2021-11, with the labels that each got.

#215 Fix formatting for nested code elements in README.md
  README.md
Labels: documentation

#207 Tutorial rewrite
  docs/fides/docs/development/documentation.md
  docs/fides/docs/tutorial/add.md
  docs/fides/docs/tutorial/ci.md
  docs/fides/docs/tutorial/dataset.md
  docs/fides/docs/tutorial/evaluate.md
  docs/fides/docs/tutorial/google.md
  docs/fides/docs/tutorial/index.md
  docs/fides/docs/tutorial/overview.md
  docs/fides/docs/tutorial/pass.md
  docs/fides/docs/tutorial/policy.md
  docs/fides/docs/tutorial/system.md
  docs/fides/docs/tutorial/taxonomy.md
  docs/fides/mkdocs.yml
Labels: documentation, dev experience

#224 Run migrations on API initialization, add `/admin/db/{action}` endpoints
  docs/fides/docs/api/index.md
  docs/fides/docs/getting_started/docker.md
  fidesctl/Dockerfile
  fidesctl/src/fidesapi/crud.py
  fidesctl/src/fidesapi/database.py
  fidesctl/src/fidesapi/main.py
  fidesctl/src/fidesctl/cli/cli.py
  fidesctl/src/fidesctl/core/api.py
  fidesctl/tests/conftest.py
Labels: documentation, enhancement

#231 Skip invalid manifest files
  fidesctl/src/fideslang/manifests.py
Labels: bug

#239 updating links in documentation
  docs/fides/docs/cli/cli.md
  docs/fides/docs/cli/evaluate.md
  docs/fides/docs/tutorial/add.md
  docs/fides/docs/tutorial/google.md
  docs/fides/docs/tutorial/policy.md
Labels: documentation

#236 Improve API Error Handling
  docker-compose.yml
  fidesctl/Dockerfile
  fidesctl/src/fidesapi/crud.py
  fidesctl/src/fidesapi/db_session.py
  fidesctl/src/fidesapi/errors.py
  fidesctl/src/fidesapi/main.py
  fidesctl/src/fidesctl/cli/cli.py
  fidesctl/src/fidesctl/core/api_helpers.py
  fidesctl/tests/core/test_api.py
Labels: enhancement, high-risk

#235 Spin up separate database for pytest execution
  Makefile
  docker-compose.yml
  docs/fides/docs/installation/configuration.md
  docs/fides/docs/tutorial/add.md
  env_files/fidesctl.env
  fidesctl/fidesctl.toml
  fidesctl/requirements.txt
  fidesctl/src/fidesapi/database.py
  fidesctl/src/fidesapi/main.py
  fidesctl/src/fidesctl/core/config.py
  fidesctl/tests/core/test_config.py
  fidesctl/tests/test_config.toml
Labels: enhancement

#250 Add CI/CD Reference Documentation
  docs/fides/docs/ci_reference.md
  docs/fides/mkdocs.yml
Labels: documentation
