Repository ethyca/fides, pull requests merged in 2021-12, with the labels that each got.

#249 Integrate with Conda and a publish through CI
  .github/workflows/publish_package.yaml
  .github/workflows/publish_pypi.yaml
  .gitignore
  README.md
  docs/fides/docs/cli/generate-dataset.md
  docs/fides/docs/development/releases.md
  docs/fides/docs/installation/conda.md
  docs/fides/docs/installation/installation.md
  docs/fides/docs/installation/pypi.md
  docs/fides/mkdocs.yml
  fidesctl/conda/meta.yaml
  fidesctl/requirements.txt
  fidesctl/setup.py
Labels: enhancement

#275 Add a simple page for evaluations
  fidesctl/src/fidesapi/main.py
  fidesctl/src/fidesapi/view.py
  fidesctl/tests/data/failing_declaration_taxonomy.yml
Labels: enhancement

#263 Parallelize CI Jobs
  .github/workflows/pr_checks.yml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  Makefile
  docker-compose.yml
  fidesctl/Dockerfile
Labels: enhancement, help wanted, testing, dev experience, high-risk

#287 API Server Logging
  docs/fides/docs/installation/configuration.md
  fidesctl/requirements.txt
  fidesctl/src/fidesapi/alembic.ini
  fidesctl/src/fidesapi/crud.py
  fidesctl/src/fidesapi/database.py
  fidesctl/src/fidesapi/db_session.py
  fidesctl/src/fidesapi/logger.py
  fidesctl/src/fidesapi/main.py
  fidesctl/src/fidesapi/migrations/env.py
  fidesctl/src/fidesctl/cli/__init__.py
  fidesctl/src/fidesctl/core/config.py
  fidesctl/src/fidesctl/core/visualize.py
  fidesctl/tests/core/test_api.py
  fidesctl/tests/core/test_visualize.py
  fidesctl/tests/data/sample_sankey.json
  fidesctl/tests/data/sample_sunburst.json
Labels: documentation, dev experience

#286 Refactor evaluation logic
  docs/fides/docs/development/database_migration.md
  docs/fides/docs/development/overview.md
  docs/fides/mkdocs.yml
  fidesctl/src/fidesapi/migrations/versions/312aff72b275_migrate_to_usage_of_evaluation_.py
  fidesctl/src/fidesapi/sql_models.py
  fidesctl/src/fidesctl/core/evaluate.py
  fidesctl/src/fideslang/models.py
  fidesctl/src/fideslang/relationships.py
  fidesctl/tests/core/test_evaluate.py
Labels: enhancement

#290 Add `created_at` and `updated_at` columns to `FidesBase` model tables
  fidesctl/src/fidesapi/crud.py
  fidesctl/src/fidesapi/database.py
  fidesctl/src/fidesapi/main.py
  fidesctl/src/fidesapi/migrations/versions/7c851d8a102a_add_created_at_and_updated_at.py
  fidesctl/src/fidesapi/sql_models.py
  fidesctl/src/fidesctl/core/evaluate.py
Labels: maintenance

#291 Remove the `action` field from Policy manifests, add an `OTHER` match type
  README.md
  docs/fides/docs/language/resources/policy.md
  docs/fides/docs/tutorial/policy.md
  fidesctl/demo_resources/demo_policy.yml
  fidesctl/fides_resources/policy.yml
  fidesctl/src/fidesctl/core/evaluate.py
  fidesctl/src/fideslang/models.py
  fidesctl/tests/conftest.py
  fidesctl/tests/core/test_evaluate.py
  fidesctl/tests/data/failing_dataset_collection_taxonomy.yml
  fidesctl/tests/data/failing_dataset_field_taxonomy.yml
  fidesctl/tests/data/failing_dataset_taxonomy.yml
  fidesctl/tests/data/failing_declaration_taxonomy.yml
  fidesctl/tests/data/passing_declaration_taxonomy.yml
  fidesctl/tests/lang/test_models.py
  fidesctl/tests/lang/test_relationships.py
Labels: documentation, enhancement, dev experience
