Repository ethyca/fides, pull requests merged in 2022-04, with the labels that each got.

#433 Add a Version Check for the Server/CLI
  Makefile
  README.md
  docs/fides/docs/quickstart/docker.md
  docs/fides/docs/quickstart/local_full.md
  fidesctl/src/fidesapi/main.py
  fidesctl/src/fidesapi/routes/__init__.py
  fidesctl/src/fidesapi/utils/__init__.py
  fidesctl/src/fidesctl/cli/__init__.py
  fidesctl/src/fidesctl/cli/commands/annotate.py
  fidesctl/src/fidesctl/cli/commands/core.py
  fidesctl/src/fidesctl/cli/commands/crud.py
  fidesctl/src/fidesctl/cli/commands/db.py
  fidesctl/src/fidesctl/cli/commands/export.py
  fidesctl/src/fidesctl/cli/commands/generate.py
  fidesctl/src/fidesctl/cli/commands/scan.py
  fidesctl/src/fidesctl/cli/commands/util.py
  fidesctl/src/fidesctl/cli/commands/view.py
  fidesctl/src/fidesctl/cli/utils.py
  fidesctl/tests/cli/test_cli.py
  fidesctl/tests/cli/test_cli_utils.py
Labels: enhancement, dev experience

#434 Resolves system and dataset data categories on a data map
  docs/fides/docs/language/resources/dataset.md
  docs/fides/docs/language/resources/system.md
  fidesctl/src/fidesctl/core/export.py
  fidesctl/src/fidesctl/core/export_helpers.py
  fidesctl/tests/core/test_export_helpers.py
Labels: bug, documentation

#440 Implement generate dataset okta command
  .github/workflows/pr_checks.yml
  Makefile
  docs/fides/docs/guides/generate_resources.md
  fidesctl/.fides/dataset.yml
  fidesctl/setup.py
  fidesctl/src/fidesapi/migrations/versions/be432bd23596_add_fidesctl_meta_field_to_dataset.py
  fidesctl/src/fidesapi/sql_models.py
  fidesctl/src/fidesctl/cli/commands/generate.py
  fidesctl/src/fidesctl/core/annotate_dataset.py
  fidesctl/src/fidesctl/core/api_helpers.py
  fidesctl/src/fidesctl/core/dataset.py
  fidesctl/src/fideslang/models.py
  fidesctl/tests/core/test_api_helpers.py
  fidesctl/tests/core/test_dataset.py
Labels: enhancement

#454 FileNotFound from pip install
  fidesctl/MANIFEST.in
  fidesctl/src/fidesctl/core/export_helpers.py
Labels: bug

#467 Fix --manifest-dir usage documentation
  docs/fides/docs/guides/generate_resources.md
Labels: bug

#466 Implement scan dataset okta command
  Makefile
  docs/fides/docs/guides/generate_resources.md
  fidesctl/src/fidesctl/cli/commands/generate.py
  fidesctl/src/fidesctl/cli/commands/scan.py
  fidesctl/src/fidesctl/cli/options.py
  fidesctl/src/fidesctl/connectors/okta.py
  fidesctl/src/fidesctl/core/dataset.py
  fidesctl/tests/cli/test_cli.py
  fidesctl/tests/connectors/test_okta.py
  fidesctl/tests/core/test_dataset.py
Labels: enhancement

#470 Filter Okta datasets so only applications with ACTIVE status are accounted for
  fidesctl/src/fidesctl/connectors/okta.py
  fidesctl/tests/connectors/test_okta.py
Labels: bug

#465 Set Default data_responsibility_title with generate system
  fidesctl/src/fidesctl/core/export.py
  fidesctl/src/fideslang/models.py
Labels: bug

#473 add missing __init__.py
  fidesctl/src/fidesctl/cli/commands/__init__.py
  fidesctl/src/fidesctl/cli/commands/generate.py
  fidesctl/src/fidesctl/cli/commands/scan.py
  fidesctl/src/fidesctl/core/dataset.py
  fidesctl/src/fidesctl/core/system.py
Labels: bug

#476 move init to LOCAL_COMMANDS
  fidesctl/src/fidesctl/cli/__init__.py
  fidesctl/src/fidesctl/connectors/__init__.py
Labels: bug

#480 Clarify log output from `fidesctl status`
  fidesctl/src/fidesctl/cli/__init__.py
  fidesctl/src/fidesctl/cli/commands/util.py
  fidesctl/src/fidesctl/cli/utils.py
Labels: bug

#492 Fix badge links to point to actions
  README.md
Labels: bug

#494 Remove issue templates in favor of org wide templates
  .github/ISSUE_TEMPLATE/fidesctl_bug_report.md
  .github/ISSUE_TEMPLATE/fidesctl_docs_update.md
  .github/ISSUE_TEMPLATE/fidesctl_feature_request.md
Labels: enhancement

#496 Fix third country formatting on data map
  fidesctl/src/fidesctl/core/export.py
  fidesctl/src/fidesctl/core/export_helpers.py
  fidesctl/tests/core/test_export_helpers.py
Labels: bug

#453 Bump fideslog to v1.1.3, update usage patterns
  fidesctl/requirements.txt
  fidesctl/src/fidesctl/cli/commands/util.py
  fidesctl/src/fidesctl/cli/utils.py
Labels: enhancement

#521 Bump fideslog to 1.1.4
  CHANGELOG.md
  requirements.txt
Labels: bug

#523 Log in-use API server config values on startup
  CHANGELOG.md
  src/fidesapi/main.py
  src/fidesctl/core/config/api_settings.py
Labels: dev experience

#488 Run make target to build docs in pr checks
  .github/workflows/pr_checks.yml
  .github/workflows/publish_docs.yaml
  Makefile
  docs/fides/Dockerfile
Labels: enhancement

#532 Send an `AnalyticsEvent` on `fidesctl init` execution
  CHANGELOG.md
  README.md
  docs/fides/docs/quickstart/docker.md
  docs/fides/docs/quickstart/local_full.md
  docs/fides/docs/quickstart/local_standalone.md
  docs/fides/docs/tutorial/add.md
  src/fidesctl/cli/commands/util.py
  src/fidesctl/cli/utils.py
Labels: documentation, enhancement
