Repository ethyca/fides, pull requests merged in 2022-01, with the labels that each got.

#301 Fix evaluations page after evaluation model refactor
  fidesctl/src/fidesapi/view.py
  fidesctl/src/fideslang/models.py
Labels: bug

#292 Implement `scan database` command
  docs/fides/docs/guides/generate_dataset.md
  docs/fides/docs/guides/scan_resource.md
  docs/fides/mkdocs.yml
  fidesctl/src/fidesctl/cli/__init__.py
  fidesctl/src/fidesctl/cli/cli.py
  fidesctl/src/fidesctl/core/generate_dataset.py
  fidesctl/test_file.yml
  fidesctl/tests/core/test_generate_dataset.py
Labels: enhancement

#307 RK Tutorial Content and Formatting Edits
  docs/fides/docs/guides/generate_dataset.md
  docs/fides/docs/guides/scan_resource.md
  docs/fides/docs/tutorial/add.md
  docs/fides/docs/tutorial/dataset.md
  docs/fides/docs/tutorial/google.md
  docs/fides/docs/tutorial/pass.md
  docs/fides/docs/tutorial/policy.md
  docs/fides/docs/tutorial/system.md
Labels: documentation

#298 Handle Infinitely Nested Datasets
  docs/fides/docs/language/resources/dataset.md
  fidesctl/src/fidesctl/core/annotate_dataset.py
  fidesctl/src/fidesctl/core/evaluate.py
  fidesctl/src/fidesctl/core/utils.py
  fidesctl/src/fideslang/models.py
  fidesctl/tests/cli/test_cli.py
  fidesctl/tests/core/test_utils.py
  fidesctl/tests/data/failing_nested_dataset.yml
Labels: enhancement

#312 Integration with SnowFlake connector
  .github/workflows/pr_checks.yml
  Makefile
  docs/fides/docs/development/testing.md
  docs/fides/docs/guides/scan_resource.md
  fidesctl/setup.py
  fidesctl/src/fidesctl/core/generate_dataset.py
  fidesctl/tests/core/test_generate_dataset.py
  fidesctl/tests/data/example_sql/snowflake_example.sql
Labels: enhancement

#316 Add integration with redshift
  .github/workflows/pr_checks.yml
  Makefile
  docs/fides/docs/development/testing.md
  docs/fides/docs/installation/pypi.md
  fidesctl/setup.py
  fidesctl/src/fidesctl/core/generate_dataset.py
  fidesctl/tests/conftest.py
  fidesctl/tests/core/test_generate_dataset.py
  fidesctl/tests/data/example_sql/postgres_example.sql
  fidesctl/tests/data/example_sql/redshift_example.sql
Labels: enhancement
