Repository ethyca/fides, pull requests merged in 2022-07, with the labels that each got.

#842 Add Okta support to generate endpoint
  CHANGELOG.md
  src/fidesapi/routes/generate.py
  src/fidesctl/cli/commands/generate.py
  src/fidesctl/cli/commands/scan.py
  src/fidesctl/connectors/okta.py
  src/fidesctl/core/system.py
  tests/api/test_generate.py
  tests/connectors/test_okta.py
  tests/core/test_system.py
Labels: enhancement

#836 allow .git directory to be included in the build
  .dockerignore
  CHANGELOG.md
Labels: bug

#866 Add fideslib and update other dependencies
  requirements.txt
  src/fidesapi/database/database.py
Labels: enhancement

#844 Bump msw 0.29.0 to 0.43.0 in admin-ui
  .github/workflows/frontend_pr_checks.yml
  clients/admin-ui/package-lock.json
  clients/admin-ui/package.json
Labels: dependencies

#883 [#882] Docs - Explain that `analytics_id` is automatically generated by the application
  docs/fides/docs/installation/configuration.md
Labels: documentation

#849 Add db support to generate endpoint
  CHANGELOG.md
  src/fidesapi/routes/generate.py
  src/fidesctl/core/dataset.py
  src/fidesctl/core/utils.py
  tests/api/test_generate.py
  tests/core/test_dataset.py
Labels: enhancement

#865 Update fideslang to 1.1.0
  .fides/dataset.yml
  .fides/policy.yml
  .fides/system.yml
  CHANGELOG.md
  clients/admin-ui/src/types/api/models/DataCategory.ts
  clients/admin-ui/src/types/api/models/DataQualifier.ts
  clients/admin-ui/src/types/api/models/DataSubject.ts
  clients/admin-ui/src/types/api/models/DataUse.ts
  clients/admin-ui/src/types/api/models/Dataset.ts
  clients/admin-ui/src/types/api/models/Organization.ts
  clients/admin-ui/src/types/api/models/Policy.ts
  clients/admin-ui/src/types/api/models/Registry.ts
  clients/admin-ui/src/types/api/models/System.ts
  demo_resources/demo_dataset.yml
  demo_resources/demo_policy.yml
  demo_resources/demo_system.yml
  docs/fides/docs/guides/policies.md
  docs/fides/docs/language/taxonomy/data_categories.md
  docs/fides/docs/language/taxonomy/data_uses.md
  docs/fides/docs/language/taxonomy/overview.md
  docs/fides/docs/tutorial/system.md
  requirements.txt
  src/fidesapi/migrations/versions/d8f8bd52754f_add_tags_as_part_of_fideslang_1_1_0.py
  src/fidesapi/routes/datamap.py
  src/fidesapi/sql_models.py
  src/fidesctl/core/visualize.py
  tests/cli/test_cli.py
  tests/conftest.py
  tests/core/test_evaluate.py
  tests/core/test_export.py
  tests/core/test_visualize.py
  tests/data/failing_dataset_collection_taxonomy.yml
  tests/data/failing_dataset_field_taxonomy.yml
  tests/data/failing_dataset_taxonomy.yml
  tests/data/failing_declaration_taxonomy.yml
  tests/data/failing_nested_dataset.yml
  tests/data/passing_declaration_taxonomy.yml
  tests/data/sample_hierarchy_figures.json
Labels: enhancement, maintenance

#814 BigQuery Connector
  .github/workflows/code_checks.yml
  CHANGELOG.md
  docs/fides/docs/guides/generate_resources.md
  noxfiles/ci_nox.py
  optional-requirements.txt
  requirements.txt
  setup.py
  src/fidesctl/cli/commands/generate.py
  src/fidesctl/cli/utils.py
  src/fidesctl/connectors/bigquery.py
  src/fidesctl/connectors/models.py
  src/fidesctl/core/config/credentials_settings.py
  src/fidesctl/core/dataset.py
  tests/cli/test_cli.py
  tests/cli/test_cli_utils.py
  tests/test_config.toml
Labels: enhancement

#901 CI Production Workflows for Docker and Docs
  .github/workflows/docker.yaml
  .github/workflows/publish_docs.yaml
  CHANGELOG.md
  noxfiles/docker_nox.py
Labels: bug

#913 Merge fidesctl config with fideslib config
  .fides/fidesctl.toml
  CHANGELOG.md
  docker-compose.yml
  docs/fides/docs/installation/configuration.md
  requirements.txt
  src/fidesctl/api/database/session.py
  src/fidesctl/api/main.py
  src/fidesctl/api/migrations/env.py
  src/fidesctl/api/routes/admin.py
  src/fidesctl/api/routes/health.py
  src/fidesctl/cli/commands/util.py
  src/fidesctl/core/config/__init__.py
  src/fidesctl/core/config/api_settings.py
  src/fidesctl/core/config/cli_settings.py
  src/fidesctl/core/config/database_settings.py
  src/fidesctl/core/config/logging_settings.py
  src/fidesctl/core/config/security_settings.py
  src/fidesctl/core/config/user_settings.py
  src/fidesctl/core/config/utils.py
  tests/core/test_config.py
  tests/core/test_utils.py
  tests/test_config.toml
  tests/test_invalid_config.toml
Labels: enhancement

#938 Dispatch a repository event on new published releases
  .github/workflows/release_event.yml
  CHANGELOG.md
Labels: dev experience, github_actions

#939 Generate systems from get tagging resources call
  CHANGELOG.md
  docs/fides/docs/guides/generate_resources.md
  src/fidesctl/cli/commands/generate.py
  src/fidesctl/cli/commands/scan.py
  src/fidesctl/ctl/connectors/aws.py
  src/fidesctl/ctl/core/system.py
  tests/ctl/core/test_system.py
Labels: enhancement

#943 Add push command to deprecate apply
  CHANGELOG.md
  README.md
  docs/fides/docs/cicd/overview.md
  docs/fides/docs/guides/generating_datamap.md
  src/fidesctl/cli/__init__.py
  src/fidesctl/cli/commands/core.py
  src/fidesctl/ctl/core/push.py
  tests/ctl/cli/test_cli.py
  tests/ctl/core/test_apply.py
Labels: enhancement
