Repository ethyca/fides, pull requests merged in 2022-10, with the labels that each got.

#1171 Make `optional-requirements.txt` a source of version truth
  CHANGELOG.md
  MANIFEST.in
  pyproject.toml
  setup.py
Labels: dev experience, high-risk, dependencies, python, Unified Fides, run unsafe ci checks

#1178 [Unified Fides] Address Remaining Failing Fidesops-Related Test Failures
  src/fides/api/ctl/routes/health.py
  src/fides/api/ctl/routes/user.py
  src/fides/api/main.py
  tests/ops/api/v1/endpoints/test_health_endpoints.py
  tests/ops/integration_test_config.toml
  tests/ops/integration_tests/test_execution.py
  tests/ops/integration_tests/test_sql_task.py
  tests/ops/service/connectors/test_saas_queryconfig.py
Labels: Unified Fides

#1162 [Unified Fides] Logging too much PII because Test Mode is True by Default
  src/fides/api/ops/service/connectors/base_connector.py
Labels: Unified Fides

#1182 [Unified Fides] Reduce Idle Health Check Connections
  src/fides/api/ctl/database/database.py
  src/fides/api/ctl/deps.py
  src/fides/api/ctl/routes/health.py
  src/fides/api/ops/api/deps.py
  tests/ctl/core/test_api.py
Labels: Unified Fides

#1189 Create rate limiter that interacts with Redis
  CHANGELOG.md
  src/fides/api/ops/service/connectors/limiter/__init__.py
  src/fides/api/ops/service/connectors/limiter/rate_limiter.py
  tests/ops/integration_tests/limiter/__init__.py
  tests/ops/integration_tests/limiter/test_rate_limiter.py
Labels: enhancement

#1200 1184 allow delete-only saas endpoints
  CHANGELOG.md
  data/saas/config/saas_example_config.yml
  data/saas/dataset/saas_example_dataset.yml
  src/fides/api/ops/schemas/saas/saas_config.py
  src/fides/api/ops/service/connectors/saas_connector.py
  tests/ops/api/v1/endpoints/test_saas_config_endpoints.py
  tests/ops/models/test_saasconfig.py
  tests/ops/service/connectors/test_saas_connector.py
Labels: run unsafe ci checks

#1282 Updating call to core config for SaaS connector tests
  noxfiles/ci_nox.py
  tests/ops/fixtures/saas/hubspot_fixtures.py
  tests/ops/integration_tests/saas/test_adobe_campaign_task.py
  tests/ops/integration_tests/saas/test_auth0_task.py
  tests/ops/integration_tests/saas/test_hubspot_task.py
  tests/ops/integration_tests/saas/test_outreach_task.py
  tests/ops/integration_tests/saas/test_salesforce_task.py
  tests/ops/integration_tests/saas/test_segment_task.py
  tests/ops/integration_tests/saas/test_sendgrid_task.py
  tests/ops/integration_tests/saas/test_shopify_task.py
  tests/ops/integration_tests/saas/test_stripe_task.py
  tests/ops/integration_tests/saas/test_zendesk_task.py
Labels: run unsafe ci checks

#1286 Fix M1 Docker Emulation
  Dockerfile
  MANIFEST.in
  dangerous-requirements.txt
  docs/fides/docs/development/overview.md
  mssql-requirements.txt
  noxfiles/docker_nox.py
  optional-requirements.txt
  setup.py
  tests/ops/integration_tests/setup_scripts/mssql_setup.py
Labels: run unsafe ci checks

#1263 Notify fidesctl-plus and fidesops-plus on new releases
  .github/workflows/release_event.yml
  CHANGELOG.md
Labels: bug, dev experience, github_actions, Unified Fides, hacktoberfest-accepted

#1403 1229/Add splash to config
  clients/admin-ui/public/images/config_splash.svg
  clients/admin-ui/src/features/common/Layout.tsx
  clients/admin-ui/src/features/config-wizard/setup.tsx
  clients/admin-ui/src/pages/config-wizard/index.tsx
Labels: UI

#1294 Adding Rollbar erasure
  CHANGELOG.md
  data/saas/config/rollbar_config.yml
  tests/ops/fixtures/saas/rollbar_fixtures.py
  tests/ops/integration_tests/saas/test_rollbar_task.py
Labels: run unsafe ci checks

#1420 1184 allow delete only saas endpoints
  src/fides/api/ops/schemas/saas/saas_config.py
  tests/ops/models/test_saasconfig.py
  tests/ops/service/connectors/test_saas_connector.py
Labels: run unsafe ci checks

#1269 UI and back-end changes for external dataset reference configuration
  clients/admin-ui/src/features/connection-type/types.ts
  clients/admin-ui/src/features/datastore-connections/add-connection/forms/ConnectorParametersForm.tsx
  data/saas/config/saas_example_config.yml
  data/saas/config/saas_external_example_config.yml
  data/saas/dataset/saas_example_dataset.yml
  docs/fides/docs/saas_connectors/saas_config.md
  src/fides/api/ops/api/v1/endpoints/connection_endpoints.py
  src/fides/api/ops/api/v1/endpoints/connection_type_endpoints.py
  src/fides/api/ops/api/v1/endpoints/dataset_endpoints.py
  src/fides/api/ops/api/v1/endpoints/saas_config_endpoints.py
  src/fides/api/ops/models/datasetconfig.py
  src/fides/api/ops/schemas/connection_configuration/__init__.py
  src/fides/api/ops/schemas/connection_configuration/connection_secrets_saas.py
  src/fides/api/ops/schemas/saas/saas_config.py
  src/fides/api/ops/service/connectors/saas_query_config.py
  tests/ops/api/v1/endpoints/test_connection_config_endpoints.py
  tests/ops/fixtures/saas/connection_template_fixtures.py
  tests/ops/fixtures/saas_example_fixtures.py
  tests/ops/models/test_datasetconfig.py
  tests/ops/models/test_saasconfig.py
  tests/ops/schemas/connection_configuration/test_connection_secrets_saas.py
  tests/ops/service/connectors/test_saas_connector.py
  tests/ops/service/connectors/test_saas_queryconfig.py
Labels: run unsafe ci checks

#1446 Remove superfluous `CODEOWNERS`
  .github/CODEOWNERS
  CHANGELOG.md
Labels: bug, dev experience, Unified Fides, hacktoberfest-accepted

#1472 Fix mypy error
  src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_doordash.py
Labels: run unsafe ci checks

#1441 Fix inconsistent SaaS connector tests
  data/saas/config/auth0_config.yml
  data/saas/config/datadog_config.yml
  data/saas/config/firebase_auth_config.yml
  data/saas/config/shopify_config.yml
  data/saas/dataset/adobe_campaign_dataset.yml
  data/saas/dataset/auth0_dataset.yml
  data/saas/dataset/firebase_auth_dataset.yml
  docs/fides/docs/getting-started/database_connectors.md
  pyproject.toml
  src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_doordash.py
  tests/ops/fixtures/saas/braze_fixtures.py
  tests/ops/fixtures/saas/doordash_fixtures.py
  tests/ops/fixtures/saas/rollbar_fixtures.py
  tests/ops/fixtures/saas/shopify_fixtures.py
  tests/ops/fixtures/saas/square_fixtures.py
  tests/ops/fixtures/saas/zendesk_fixtures.py
  tests/ops/integration_tests/saas/request_override/test_firebase_auth_task.py
  tests/ops/integration_tests/saas/request_override/test_mailchimp_override_task.py
  tests/ops/integration_tests/saas/test_adobe_campaign_task.py
  tests/ops/integration_tests/saas/test_auth0_task.py
  tests/ops/integration_tests/saas/test_braze_task.py
  tests/ops/integration_tests/saas/test_datadog_task.py
  tests/ops/integration_tests/saas/test_hubspot_task.py
  tests/ops/integration_tests/saas/test_mailchimp_task.py
  tests/ops/integration_tests/saas/test_outreach_task.py
  tests/ops/integration_tests/saas/test_segment_task.py
  tests/ops/integration_tests/saas/test_sendgrid_task.py
  tests/ops/integration_tests/saas/test_sentry_task.py
  tests/ops/integration_tests/saas/test_shopify_task.py
  tests/ops/integration_tests/saas/test_square_task.py
  tests/ops/integration_tests/saas/test_stripe_task.py
  tests/ops/integration_tests/saas/test_zendesk_task.py
  tests/ops/service/connectors/test_saas_queryconfig.py
Labels: run unsafe ci checks

#1483 Making offset limit optional
  docs/fides/docs/saas_connectors/saas_pagination.md
  src/fides/api/ops/schemas/saas/strategy_configuration.py
  src/fides/api/ops/service/pagination/pagination_strategy_offset.py
  tests/ops/service/pagination/test_pagination_strategy_offset.py
Labels: run unsafe ci checks

#1459 587, 588, 598/in progress infra scan, cancel scan modal, register systems modal
  clients/admin-ui/cypress/e2e/config-wizard.cy.ts
  clients/admin-ui/src/features/common/Icon/Warning.tsx
  clients/admin-ui/src/features/common/Icon/index.tsx
  clients/admin-ui/src/features/common/WarningModal.tsx
  clients/admin-ui/src/features/config-wizard/AuthenticateAwsForm.tsx
  clients/admin-ui/src/features/config-wizard/ScanResultsForm.tsx
Labels: UI, AWS Scanning UI

#1527 232/Update step 2 of config wizard
  clients/admin-ui/cypress/e2e/config-wizard.cy.ts
  clients/admin-ui/src/features/config-wizard/AddSystemForm.tsx
  clients/admin-ui/src/features/config-wizard/AuthenticateAwsForm.tsx
  clients/admin-ui/src/features/config-wizard/constants.tsx
Labels: UI, Fides NUX Improvements

#1526 231/Update to step 1 in config wizard
  clients/admin-ui/src/features/config-wizard/OrganizationInfoForm.tsx
Labels: UI, Fides NUX Improvements

#1513 Domo erasures
  data/saas/config/domo_config.yml
  data/saas/dataset/domo_dataset.yml
  noxfiles/dev_nox.py
  src/fides/api/ops/service/saas_request/__init__.py
  src/fides/api/ops/service/saas_request/override_implementations/domo_request_overrides.py
  src/fides/ctl/core/utils.py
  tests/ops/fixtures/application_fixtures.py
  tests/ops/fixtures/saas/domo_fixtures.py
  tests/ops/integration_tests/saas/test_domo_task.py
Labels: run unsafe ci checks

#1567 233/Update AWS scanner page header
  clients/admin-ui/src/features/config-wizard/AuthenticateAwsForm.tsx
Labels: Fides NUX Improvements

#1554 Add a `plus_system_scans` table to the database
  .fides/dataset.yml
  CHANGELOG.md
  src/fidesctl/api/ctl/migrations/versions/6b9885e68cbb_add_plus_system_scans_table.py
  src/fidesctl/api/ctl/sql_models.py
  src/fidesctl/ctl/core/utils.py
Labels: enhancement, python, hacktoberfest-accepted

#1582 Update `CHANGELOG.md` for patch release 1.9.5
  CHANGELOG.md
Labels: documentation, maintenance, hacktoberfest-accepted

#1433 Integrate redis rate limiter with saas connectors
  CHANGELOG.md
  docs/fides/docs/saas_connectors/saas_config.md
  docs/fides/docs/saas_connectors/saas_rate_limiting.md
  docs/fides/mkdocs.yml
  src/fides/api/ops/schemas/limiter/__init__.py
  src/fides/api/ops/schemas/limiter/rate_limit_config.py
  src/fides/api/ops/schemas/saas/saas_config.py
  src/fides/api/ops/service/connectors/limiter/rate_limiter.py
  src/fides/api/ops/service/connectors/saas/authenticated_client.py
  src/fides/api/ops/service/connectors/saas_connector.py
  src/fides/api/ops/service/pagination/pagination_strategy.py
  src/fides/api/ops/service/pagination/pagination_strategy_cursor.py
  src/fides/api/ops/service/pagination/pagination_strategy_link.py
  src/fides/api/ops/service/pagination/pagination_strategy_offset.py
  tests/ops/fixtures/saas/mailchimp_fixtures.py
  tests/ops/fixtures/saas/request_override/mailchimp_override_fixtures.py
  tests/ops/integration_tests/limiter/test_rate_limiter.py
  tests/ops/integration_tests/test_connection_configuration_integration.py
  tests/ops/schemas/limiter/__init__.py
  tests/ops/schemas/limiter/test_rate_limit_config.py
  tests/ops/service/connectors/saas/test_authenticated_client.py
  tests/ops/service/connectors/test_saas_connector.py
  tests/ops/service/privacy_request/request_runner_service_test.py
Labels: enhancement, run unsafe ci checks

#1583 Merge `deploy-1.9.5`
  .fides/db_dataset.yml
  CHANGELOG.md
  src/fides/api/ctl/migrations/versions/6b9885e68cbb_add_plus_system_scans_table.py
  src/fides/api/ctl/sql_models.py
  src/fides/ctl/core/parse.py
Labels: documentation, enhancement, python, hacktoberfest-accepted

#1568 234/wizard nav updates
  clients/admin-ui/src/features/config-wizard/AuthenticateAwsForm.tsx
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/ScanResultsForm.tsx
  clients/admin-ui/src/features/system/DescribeSystemStep.tsx
  clients/admin-ui/src/features/system/ManualSystemFlow.tsx
  clients/admin-ui/src/features/system/PrivacyDeclarationForm.tsx
  clients/admin-ui/src/features/system/PrivacyDeclarationStep.tsx
  clients/admin-ui/src/features/system/ReviewSystemStep.tsx
Labels: Fides NUX Improvements

#1616 236/Finish setup step
  clients/admin-ui/cypress/e2e/systems.cy.ts
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/SuccessPage.tsx
  clients/admin-ui/src/features/config-wizard/ViewYourDataMapPage.tsx
  clients/admin-ui/src/features/system/ManualSystemFlow.tsx
  clients/admin-ui/src/features/system/SystemRegisterSuccess.tsx
Labels: Fides NUX Improvements

#1608 1479/systems without declarations default
  clients/admin-ui/cypress/e2e/config-wizard.cy.ts
  clients/admin-ui/src/features/config-wizard/AddSystemForm.tsx
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/ScanResultsForm.tsx
Labels: Fides NUX Improvements
