Repository ethyca/fides, pull requests merged in 2022-09, with the labels that each got.

#1026 remove exclude_unset=True to return clean diff
  CHANGELOG.md
  noxfiles/ci_nox.py
  src/fidesctl/ctl/core/push.py
Labels: bug

#1087 ui/datasets: Refactor selectors
  clients/ctl/admin-ui/cypress/e2e/datasets.cy.ts
  clients/ctl/admin-ui/src/features/dataset/DatabaseConnectForm.tsx
  clients/ctl/admin-ui/src/features/dataset/DatasetCollectionView.tsx
  clients/ctl/admin-ui/src/features/dataset/DatasetFieldsTable.tsx
  clients/ctl/admin-ui/src/features/dataset/DatasetTable.tsx
  clients/ctl/admin-ui/src/features/dataset/DatasetYamlForm.tsx
  clients/ctl/admin-ui/src/features/dataset/EditCollectionDrawer.tsx
  clients/ctl/admin-ui/src/features/dataset/EditDatasetDrawer.tsx
  clients/ctl/admin-ui/src/features/dataset/EditFieldDrawer.tsx
  clients/ctl/admin-ui/src/features/dataset/dataset.slice.ts
  clients/ctl/admin-ui/src/features/dataset/types.ts
  clients/ctl/admin-ui/src/pages/dataset/index.tsx
Labels: Fides Classify UI

#1103 Bump fideslang to 1.3.0
  .fides/dataset.yml
  CHANGELOG.md
  requirements.txt
  src/fidesctl/api/ctl/migrations/versions/6bd93cb0603d_add_egress_and_ingress_to_systems.py
  src/fidesctl/api/ctl/sql_models.py
Labels: dependencies

#1107 Prepare 1.8.5 release
  CHANGELOG.md
Labels: documentation

#1105 Combine safe and unsafe checks into a single worfklow
  .fides/db_dataset.yml
  .fides/systems.yml
  .github/workflows/code_checks.yml
  .github/workflows/unsafe_code_checks.yml
  noxfiles/ci_nox.py
Labels: run unsafe ci checks

#1136 Bump fideslang to 1.3.1
  CHANGELOG.md
  requirements.txt
Labels: dependencies

#1135 Make nox test name sessions more logical
  .github/workflows/backend_checks.yml
  noxfiles/ci_nox.py
  noxfiles/dev_nox.py
Labels: run unsafe ci checks
