Repository ethyca/fides, pull requests merged in 2022-11, with the labels that each got.

#1652 Add Hubspot scopes to documentation
  docs/fides/docs/saas_connectors/example_configs/hubspot.md
Labels: documentation

#1634 1479/systems without declarations default
  clients/admin-ui/cypress/e2e/config-wizard.cy.ts
  clients/admin-ui/src/features/common/WarningModal.tsx
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/ScanResultsForm.tsx
  clients/admin-ui/src/features/config-wizard/SuccessPage.tsx
  clients/admin-ui/src/features/system/SystemRegisterSuccess.tsx
  clients/admin-ui/src/features/system/system.slice.ts
Labels: Fides NUX Improvements

#1664 Small updates to README
  README.md
Labels: documentation

#1655 1629 custom auth strategy adobe campaign
  data/saas/config/adobe_campaign_config.yml
  src/fides/api/ops/service/saas_request/__init__.py
  src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_adobe_campaign.py
  tests/ops/fixtures/saas/adobe_campaign_fixtures.py
Labels: run unsafe ci checks

#1666 Bump fideslog to v1.2.10
  CHANGELOG.md
  requirements.txt
Labels: bug, dependencies

#1683 Update OpenSSL-affected requirements
  CHANGELOG.md
  optional-requirements.txt
  requirements.txt
Labels: run unsafe ci checks

#1674 Fix Missing Word in Identity Modal
  CHANGELOG.md
  clients/privacy-center/components/modals/VerificationForm.tsx
Labels: UI

#1694 Show a helpful error message if Docker daemon is not running during "fides deploy"
  CHANGELOG.md
  src/fides/ctl/core/deploy.py
Labels: enhancement, dev experience, python

#1679 Make all dependencies part of the standard install except for known-dangerous packages
  .github/workflows/backend_checks.yml
  .github/workflows/cli_checks.yml
  .github/workflows/static_code_checks.yml
  CHANGELOG.md
  Dockerfile
  dangerous-requirements.txt
  docs/fides/docs/installation/configuration.md
  docs/fides/docs/installation/overview.md
  docs/fides/docs/installation/pypi.md
  docs/fides/docs/installation/requirements.md
  docs/fides/mkdocs.yml
  noxfiles/ci_nox.py
  optional-requirements.txt
  requirements.txt
  setup.py
  src/fides/api/ctl/routes/generate.py
  src/fides/api/ctl/routes/util.py
  src/fides/api/ctl/routes/validate.py
  src/fides/api/ops/models/datasetconfig.py
  src/fides/api/ops/tasks/storage.py
  src/fides/api/ops/util/storage_authenticator.py
  src/fides/ctl/core/system.py
Labels: run unsafe ci checks

#1702 Refactor CI workflows to leverage matrices for less code duplication
  .github/workflows/backend_checks.yml
  .github/workflows/static_code_checks.yml
Labels: run unsafe ci checks

#1713 1573/Tooltip for password requirements
  clients/admin-ui/src/features/user-management/UserForm.tsx
Labels: Fides NUX Improvements

#1693 238/Scan complete success alert
  clients/admin-ui/src/features/config-wizard/AuthenticateAwsForm.tsx
  clients/admin-ui/src/features/config-wizard/ScanResultsForm.tsx
Labels: Fides NUX Improvements

#1737 230/Login defaults
  clients/admin-ui/src/constants.ts
  clients/admin-ui/src/features/config-wizard/setup.tsx
  clients/admin-ui/src/pages/login.tsx
Labels: Fides NUX Improvements

#1824 docs: fix typo in Postgres, remove connection string
  CHANGELOG.md
  docs/fides/docs/installation/configuration.md
Labels: documentation

#1841 1837/Update cypress tests for okta
  clients/admin-ui/cypress/e2e/config-wizard.cy.ts
Labels: bug
