Repository ethyca/fides, pull requests merged in 2022-05, with the labels that each got.

#520 Refactor with_analytics function into a decorator
  CHANGELOG.md
  src/fidesctl/cli/commands/annotate.py
  src/fidesctl/cli/commands/core.py
  src/fidesctl/cli/commands/crud.py
  src/fidesctl/cli/commands/db.py
  src/fidesctl/cli/commands/export.py
  src/fidesctl/cli/commands/generate.py
  src/fidesctl/cli/commands/scan.py
  src/fidesctl/cli/commands/util.py
  src/fidesctl/cli/commands/view.py
  src/fidesctl/cli/utils.py
Labels: enhancement

#540 Properly Load Enum Values for DataSubjectRightsEnum
  CHANGELOG.md
  src/fidesctl/core/export_helpers.py
  tests/core/test_export_helpers.py
Labels: bug

#558 Include Tests in static code analysis
  CHANGELOG.md
  noxfiles/ci_nox.py
  noxfiles/constants_nox.py
  noxfiles/docker_nox.py
  noxfiles/docs_nox.py
  requirements.txt
  setup.cfg
  tests/__init__.py
  tests/cli/__init__.py
  tests/cli/test_cli.py
  tests/cli/test_cli_utils.py
  tests/conftest.py
  tests/connectors/__init__.py
  tests/connectors/test_okta.py
  tests/core/__init__.py
  tests/core/test_api.py
  tests/core/test_api_helpers.py
  tests/core/test_apply.py
  tests/core/test_config.py
  tests/core/test_config_utils.py
  tests/core/test_dataset.py
  tests/core/test_evaluate.py
  tests/core/test_export.py
  tests/core/test_export_helpers.py
  tests/core/test_filters.py
  tests/core/test_system.py
  tests/core/test_utils.py
  tests/core/test_visualize.py
  tests/lang/__init__.py
  tests/lang/test_manifests.py
  tests/lang/test_parse.py
  tests/lang/test_relationships.py
  tests/lang/test_validation.py
Labels: dev experience

#609 Update fideslog to v1.1.5
  CHANGELOG.md
  requirements.txt
Labels: bug, dependencies, python

#602 update the type param for docs_build nox command
  noxfiles/docs_nox.py
Labels: bug

#619 Remove fideslang module in favor of fideslang package
  CHANGELOG.md
  requirements.txt
  src/fidesapi/database/database.py
  src/fidesapi/routes/crud.py
  src/fidesapi/routes/visualize.py
  src/fidesctl/cli/options.py
  src/fidesctl/connectors/okta.py
  src/fidesctl/core/annotate_dataset.py
  src/fidesctl/core/api_helpers.py
  src/fidesctl/core/apply.py
  src/fidesctl/core/dataset.py
  src/fidesctl/core/evaluate.py
  src/fidesctl/core/export.py
  src/fidesctl/core/export_helpers.py
  src/fidesctl/core/parse.py
  src/fidesctl/core/system.py
  src/fidesctl/core/utils.py
  src/fideslang/__init__.py
  src/fideslang/default_fixtures.py
  src/fideslang/default_taxonomy.py
  src/fideslang/manifests.py
  src/fideslang/models.py
  src/fideslang/parse.py
  src/fideslang/relationships.py
  src/fideslang/utils.py
  src/fideslang/validation.py
  tests/conftest.py
  tests/connectors/test_okta.py
  tests/core/test_api.py
  tests/core/test_api_helpers.py
  tests/core/test_apply.py
  tests/core/test_dataset.py
  tests/core/test_evaluate.py
  tests/core/test_export.py
  tests/core/test_export_helpers.py
  tests/core/test_filters.py
  tests/core/test_system.py
  tests/core/test_utils.py
  tests/lang/__init__.py
  tests/lang/test_manifests.py
  tests/lang/test_parse.py
  tests/lang/test_relationships.py
  tests/lang/test_validation.py
Labels: enhancement

#661 complex character handling in test_dataset.py
  CHANGELOG.md
  tests/core/test_dataset.py
Labels: bug

#655 Include default_organization in data map export if no Organization found
  src/fidesctl/core/export_helpers.py
  tests/cli/test_cli.py
Labels: bug

#684 Fix local demo_resources evaluation
  CHANGELOG.md
  src/fidesctl/core/evaluate.py
  tests/cli/test_cli.py
  tests/core/test_evaluate.py
Labels: bug

#694 Add credentials config that supports custom keys
  CHANGELOG.md
  docs/fides/docs/guides/generate_resources.md
  docs/fides/docs/installation/configuration.md
  docs/fides/docs/tutorial/dataset.md
  noxfiles/ci_nox.py
  src/fidesctl/cli/commands/generate.py
  src/fidesctl/cli/commands/scan.py
  src/fidesctl/cli/options.py
  src/fidesctl/cli/utils.py
  src/fidesctl/connectors/okta.py
  src/fidesctl/core/config/__init__.py
  src/fidesctl/core/config/credentials_settings.py
  src/fidesctl/core/dataset.py
  src/fidesctl/core/system.py
  tests/cli/test_cli.py
  tests/cli/test_cli_utils.py
  tests/connectors/test_okta.py
  tests/core/config/test_credentials_settings.py
  tests/core/test_config.py
  tests/core/test_dataset.py
  tests/core/test_system.py
  tests/test_config.toml
Labels: enhancement

#642 Create a New Generate Endpoint
  CHANGELOG.md
  pyproject.toml
  src/fidesapi/main.py
  src/fidesapi/routes/generate.py
  src/fidesapi/routes/util.py
  tests/api/__init__.py
  tests/api/test_generate.py
  tests/api/test_util.py
Labels: enhancement, do not merge

#548 Audit Command for Resource Compliance
  CHANGELOG.md
  demo_resources/demo_system.yml
  docs/fides/docs/guides/generating_datamap.md
  src/fidesctl/cli/commands/core.py
  src/fidesctl/cli/utils.py
  src/fidesctl/core/audit.py
  tests/cli/test_cli.py
  tests/core/test_audit.py
Labels: enhancement
