Repository ethyca/fides, pull requests merged in 2022-06, with the labels that each got.

#725 Refactor Export to remove CLI specific request methods
  CHANGELOG.md
  src/fidesctl/core/export.py
  src/fidesctl/core/export_helpers.py
  tests/core/test_export.py
Labels: maintenance

#719 [#569, #570] Organization setup
  clients/admin-ui/src/features/common/Header.tsx
  clients/admin-ui/src/features/common/Icon/Question.tsx
  clients/admin-ui/src/features/common/Icon/StepperCircle.tsx
  clients/admin-ui/src/features/common/Icon/VerticalLine.tsx
  clients/admin-ui/src/features/common/Icon/index.tsx
  clients/admin-ui/src/features/common/Stepper.tsx
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/OrganizationInfoForm.tsx
  clients/admin-ui/src/features/config-wizard/constants.tsx
  clients/admin-ui/src/features/config-wizard/organization.slice.ts
  clients/admin-ui/src/features/config-wizard/setup.tsx
  clients/admin-ui/src/features/config-wizard/types.tsx
  clients/admin-ui/src/pages/config-wizard/index.tsx
Labels: enhancement

#741 [#573] Add system selection page
  clients/admin-ui/src/features/common/Icon/AWSLogo.tsx
  clients/admin-ui/src/features/common/Icon/ManualSetup.tsx
  clients/admin-ui/src/features/common/Icon/OktaLogo.tsx
  clients/admin-ui/src/features/common/Icon/index.tsx
  clients/admin-ui/src/features/config-wizard/AddSystemForm.tsx
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/constants.tsx
Labels: enhancement

#721 Endpoint to return a Data Map
  CHANGELOG.md
  src/fidesapi/main.py
  src/fidesapi/routes/datamap.py
  src/fidesctl/core/export_helpers.py
  tests/api/test_datamap.py
  tests/conftest.py
Labels: enhancement

#751 Refactor Okta operations to scan/generate systems
  CHANGELOG.md
  docs/fides/docs/guides/generate_resources.md
  src/fidesctl/cli/commands/generate.py
  src/fidesctl/cli/commands/scan.py
  src/fidesctl/connectors/okta.py
  src/fidesctl/core/dataset.py
  src/fidesctl/core/system.py
  tests/cli/test_cli.py
  tests/connectors/test_okta.py
  tests/core/test_dataset.py
  tests/core/test_system.py
Labels: enhancement

#750 [747] Stepper updates
  clients/admin-ui/src/features/common/Icon/StepperCircle.tsx
  clients/admin-ui/src/features/common/Icon/StepperCircleCheckmark.tsx
  clients/admin-ui/src/features/common/Icon/VerticalLine.tsx
  clients/admin-ui/src/features/common/Icon/index.tsx
  clients/admin-ui/src/features/common/Stepper.tsx
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
Labels: enhancement

#761 Handling an invalidly generated fides_key
  CHANGELOG.md
  src/fidesctl/core/dataset.py
  src/fidesctl/core/utils.py
  tests/core/test_utils.py
Labels: bug

#775 1.6.1 changelog and docs updates
  CHANGELOG.md
  docs/fides/docs/development/releases.md
Labels: documentation

#772 [579][748]/manual entry & save/cancel progress in config wizard
  clients/admin-ui/src/app/store.ts
  clients/admin-ui/src/features/common/HorizontalStepper.tsx
  clients/admin-ui/src/features/common/Icon/HorizontalLine.tsx
  clients/admin-ui/src/features/common/Icon/index.tsx
  clients/admin-ui/src/features/common/Stepper.tsx
  clients/admin-ui/src/features/common/form/inputs.tsx
  clients/admin-ui/src/features/common/helpers.ts
  clients/admin-ui/src/features/config-wizard/AddSystemForm.tsx
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/DescribeSystemsForm.tsx
  clients/admin-ui/src/features/config-wizard/OrganizationInfoForm.tsx
  clients/admin-ui/src/features/config-wizard/constants.tsx
  clients/admin-ui/src/features/config-wizard/organization.slice.ts
  clients/admin-ui/src/features/system/system.slice.ts
Labels: enhancement

#791 [#599]Finish page
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/ViewYourDataMapPage.tsx
  clients/admin-ui/src/features/config-wizard/constants.tsx
Labels: enhancement

#787 [#723]/privacy declaration & review page
  CHANGELOG.md
  clients/admin-ui/src/app/store.ts
  clients/admin-ui/src/features/common/HorizontalStepper.tsx
  clients/admin-ui/src/features/common/Icon/Add.tsx
  clients/admin-ui/src/features/common/Icon/index.tsx
  clients/admin-ui/src/features/common/form/inputs.tsx
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/DescribeSystemsForm.tsx
  clients/admin-ui/src/features/config-wizard/OrganizationInfoForm.tsx
  clients/admin-ui/src/features/config-wizard/PrivacyDeclarationForm.tsx
  clients/admin-ui/src/features/config-wizard/ReviewSystemForm.tsx
  clients/admin-ui/src/features/data-qualifier/data-qualifier.slice.ts
  clients/admin-ui/src/features/data-qualifier/types.ts
  clients/admin-ui/src/features/data-subjects/data-subject.slice.ts
  clients/admin-ui/src/features/data-subjects/types.ts
  clients/admin-ui/src/features/data-use/data-use.slice.ts
  clients/admin-ui/src/features/data-use/types.ts
  clients/admin-ui/src/features/system/types.ts
Labels: enhancement

#802 [#597]/success page
  clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
  clients/admin-ui/src/features/config-wizard/ReviewSystemForm.tsx
  clients/admin-ui/src/features/config-wizard/SuccessPage.tsx
Labels: enhancement

#779 Human-readable column names in datamap response
  CHANGELOG.md
  src/fidesapi/routes/datamap.py
  src/fidesctl/core/export.py
  src/fidesctl/core/export_helpers.py
  tests/core/test_export_helpers.py
Labels: enhancement
