Repository ethyca/fides, pull requests merged in 2022-08, with the labels that each got.

#948 Remove usage of event.ref in release workflow for publishing docs
  .github/workflows/publish_docs.yaml
Labels: bug

#955 Document the patch release process
  CHANGELOG.md
  docs/fides/docs/development/releases.md
Labels: documentation, dev experience

#964 Remove old env vars
  .github/workflows/publish_package.yaml
  CHANGELOG.md
  docker-compose.yml
  docs/fides/docs/quickstart/docker.md
  docs/fides/docs/tutorial/add.md
  setup.cfg
Labels: bug, documentation, dev experience

#965 Restore recognition of deprecated `FIDESCTL__API__` ENV variables
  CHANGELOG.md
  src/fidesctl/ctl/core/config/__init__.py
  tests/ctl/core/test_config.py
Labels: bug

#992 include fides_key in datamap api output
  CHANGELOG.md
  demo_resources/demo_system.yml
  src/fidesctl/api/ctl/routes/datamap.py
  src/fidesctl/ctl/core/export.py
  src/fidesctl/ctl/core/export_helpers.py
Labels: enhancement
