Repository ethyca/fides, pull requests merged in 2022-03, with the labels that each got.

#385 Add RDS as an aws source
  fidesctl/src/fidesctl/cli/generate_commands.py
  fidesctl/src/fidesctl/cli/scan_commands.py
  fidesctl/src/fidesctl/core/system.py
  fidesctl/tests/core/test_system.py
Labels: enhancement

#387 Implement organization level filtering for scanning resources
  fidesctl/src/fidesapi/migrations/versions/150f234ef1de_add_fidesctl_meta_to_organization_object.py
  fidesctl/src/fidesapi/sql_models.py
  fidesctl/src/fidesctl/cli/generate_commands.py
  fidesctl/src/fidesctl/cli/scan_commands.py
  fidesctl/src/fidesctl/core/filters.py
  fidesctl/src/fidesctl/core/system.py
  fidesctl/src/fideslang/models.py
  fidesctl/tests/core/test_filters.py
  fidesctl/tests/core/test_system.py
Labels: enhancement

#392 Add documentation for filtering AWS resources
  docs/fides/docs/guides/generate_resources.md
Labels: documentation

#386 Integrate fideslog for anonymous CLI analytics
  Makefile
  docs/fides/docs/installation/configuration.md
  docs/fides/docs/quickstart/docker.md
  docs/fides/docs/quickstart/local_full.md
  docs/fides/docs/quickstart/local_standalone.md
  fidesctl/.fides/fidesctl.toml
  fidesctl/Dockerfile
  fidesctl/requirements.txt
  fidesctl/src/fidesctl/cli/__init__.py
  fidesctl/src/fidesctl/cli/annotate_commands.py
  fidesctl/src/fidesctl/cli/core_commands.py
  fidesctl/src/fidesctl/cli/crud_commands.py
  fidesctl/src/fidesctl/cli/db_commands.py
  fidesctl/src/fidesctl/cli/export_commands.py
  fidesctl/src/fidesctl/cli/generate_commands.py
  fidesctl/src/fidesctl/cli/scan_commands.py
  fidesctl/src/fidesctl/cli/util_comands.py
  fidesctl/src/fidesctl/cli/utils.py
  fidesctl/src/fidesctl/cli/view_commands.py
  fidesctl/src/fidesctl/core/config/__init__.py
  fidesctl/src/fidesctl/core/config/cli_settings.py
  fidesctl/src/fidesctl/core/config/user_settings.py
  fidesctl/src/fidesctl/core/config/utils.py
  fidesctl/tests/cli/test_cli.py
  fidesctl/tests/core/test_config_utils.py
  fidesctl/tests/test_config.toml
  fidesctl/tests/test_invalid_config.toml
Labels: documentation, enhancement, high-risk

#407 Install fidesctl from source instead of pulling from pypi
  .github/workflows/publish_docs.yaml
  docs/fides/requirements.txt
Labels: bug

#405 Send "developer" analytics events in test mode
  Makefile
  fidesctl/requirements.txt
  fidesctl/src/fidesctl/cli/__init__.py
  fidesctl/src/fidesctl/cli/utils.py
  fidesctl/src/fidesctl/core/config/cli_settings.py
Labels: enhancement

#404 Remove Conda deployment from fidesctl
  .github/workflows/publish_package.yaml
  docs/fides/docs/development/releases.md
  docs/fides/docs/installation/conda.md
  docs/fides/docs/installation/installation.md
  docs/fides/mkdocs.yml
  fidesctl/conda/meta.yaml
Labels: bug

#408 Add Article 6 & 9 Privacy Notice to Data Map Export
  docs/fides/docs/guides/extending_data_use.md
  docs/fides/docs/language/taxonomy/data_uses.md
  fidesctl/demo_resources/demo_data_uses.yml
  fidesctl/src/fidesapi/migrations/versions/7a94527643a1_add_column_for_special_category_to_data_.py
  fidesctl/src/fidesapi/sql_models.py
  fidesctl/src/fidesctl/core/export.py
  fidesctl/src/fidesctl/core/export_helpers.py
  fidesctl/src/fideslang/models.py
  fidesctl/tests/core/test_export_helpers.py
Labels: enhancement

#412 Designate Role of Responsibility (Controller, Processor, Sub-Processor)
  docs/fides/docs/language/resources/system.md
  fidesctl/demo_resources/demo_system.yml
  fidesctl/src/fidesapi/migrations/versions/fdd28c39a679_add_responsibility_role_attribute_for_.py
  fidesctl/src/fidesapi/sql_models.py
  fidesctl/src/fidesctl/core/export.py
  fidesctl/src/fidesctl/core/export_helpers.py
  fidesctl/src/fidesctl/templates/fides_datamap_template.xlsx
  fidesctl/src/fideslang/models.py
  fidesctl/tests/core/test_export_helpers.py
Labels: enhancement

#422 Refactor generate/scan dataset commands so dataset is a command group
  docs/fides/docs/guides/generate_resources.md
  docs/fides/docs/language/resources/dataset.md
  docs/fides/docs/tutorial/add.md
  docs/fides/docs/tutorial/dataset.md
  fidesctl/src/fidesctl/cli/generate_commands.py
  fidesctl/src/fidesctl/cli/scan_commands.py
  fidesctl/src/fidesctl/core/dataset.py
  fidesctl/tests/cli/test_cli.py
  fidesctl/tests/core/test_dataset.py
Labels: enhancement

#421 `fidesctl apply` "upserts" resources
  fidesctl/src/fidesapi/database/crud.py
  fidesctl/src/fidesapi/database/database.py
  fidesctl/src/fidesapi/routes/crud.py
  fidesctl/src/fidesctl/cli/core_commands.py
  fidesctl/src/fidesctl/cli/options.py
  fidesctl/src/fidesctl/core/api.py
  fidesctl/src/fidesctl/core/apply.py
  fidesctl/tests/core/test_api.py
  fidesctl/tests/core/test_apply.py
Labels: enhancement, high-risk

#413 Model and Export Remaining Privacy Notice Attributes
  docs/fides/docs/guides/extending_data_use.md
  docs/fides/docs/guides/extending_taxonomy.md
  docs/fides/docs/language/taxonomy/data_categories.md
  docs/fides/docs/language/taxonomy/data_subjects.md
  docs/fides/docs/language/taxonomy/data_uses.md
  docs/fides/mkdocs.yml
  fidesctl/.fides/dataset.yml
  fidesctl/demo_resources/demo_data_subjects.yml
  fidesctl/demo_resources/demo_data_uses.yml
  fidesctl/src/fidesapi/migrations/versions/adad3be6af08_privacy_notice_attributes.py
  fidesctl/src/fidesapi/sql_models.py
  fidesctl/src/fidesctl/core/export.py
  fidesctl/src/fidesctl/core/export_helpers.py
  fidesctl/src/fideslang/models.py
  fidesctl/tests/core/test_export_helpers.py
Labels: enhancement
