Repository ethyca/fides, pull requests merged in 2023-02, with the labels that each got.

#2439 handle non-existent firebase users
  CHANGELOG.md
  src/fides/api/ops/service/saas_request/override_implementations/firebase_auth_request_overrides.py
  tests/ops/integration_tests/saas/request_override/test_firebase_auth_task.py
Labels: run unsafe ci checks

#2489 2482 privacy requests approved in quick succession error when not running worker
  CHANGELOG.md
  src/fides/api/ops/service/messaging/message_dispatch_service.py
  src/fides/api/ops/service/privacy_request/request_runner_service.py
  src/fides/api/ops/tasks/__init__.py
  src/fides/api/ops/worker/__init__.py
  src/fides/cli/commands/util.py
  tests/ctl/cli/test_cli.py
Labels: bug

#2423 2234/2235/2236/Storage and messaging provider configuration
  clients/admin-ui/cypress/e2e/privacy-requests.cy.ts
  clients/admin-ui/cypress/fixtures/privacy-requests/settings_configuration.json
  clients/admin-ui/cypress/support/stubs.ts
  clients/admin-ui/src/features/common/nav/v2/hooks.ts
  clients/admin-ui/src/features/common/nav/v2/nav-config.ts
  clients/admin-ui/src/features/privacy-requests/configuration/MailgunEmailConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/MessagingConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/S3StorageConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/StorageConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/TwilioEmailConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/TwilioSMS.tsx
  clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts
  clients/admin-ui/src/features/privacy-requests/types.ts
  clients/admin-ui/src/flags.json
  clients/admin-ui/src/pages/privacy-requests/configure.tsx
  clients/admin-ui/src/pages/privacy-requests/configure/messaging.tsx
  clients/admin-ui/src/pages/privacy-requests/configure/storage.tsx
Labels: enhancement

#2223 1875 saas connector braintree
  CHANGELOG.md
  data/saas/config/braintree_config.yml
  data/saas/dataset/braintree_dataset.yml
  data/saas/saas_connector_registry.toml
  pyproject.toml
  tests/ops/fixtures/saas/braintree_fixtures.py
  tests/ops/fixtures/saas/external_datasets/braintree.sql
  tests/ops/integration_tests/saas/test_braintree_task.py
Labels: run unsafe ci checks

#2564 [#2563] Standardise the test creds across environments
  README.md
  noxfiles/dev_nox.py
  scripts/setup/constants.py
  src/fides/core/deploy.py
  src/fides/data/sample_project/cookie_house/src/components/Landing/index.tsx
Labels: do not merge

#2576 2233/Configuration notification banner
  clients/admin-ui/src/constants.ts
  clients/admin-ui/src/features/common/Layout.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/ConfigurationNotificationBanner.tsx
  clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts
Labels: enhancement

#2600 Wunderkind Saas Consent Connector
  CHANGELOG.md
  clients/admin-ui/public/images/connector-logos/wunderkind.svg
  clients/admin-ui/src/features/datastore-connections/constants.ts
  data/saas/config/wunderkind_config.yml
  data/saas/dataset/wunderkind_dataset.yml
  data/saas/icon/wunderkind.svg
  data/saas/saas_connector_registry.toml
  tests/lib/test_oauth_util.py
  tests/ops/fixtures/saas/wunderkind_fixtures.py
  tests/ops/integration_tests/saas/test_wunderkind_task.py
Labels: run unsafe ci checks

#2602 Updating Firebase Auth to delete user
  CHANGELOG.md
  data/saas/config/firebase_auth_config.yml
  tests/ops/integration_tests/saas/request_override/test_firebase_auth_task.py
Labels: run unsafe ci checks

#2650 2528/Styles on privacy requests filters
  clients/admin-ui/src/features/privacy-requests/RequestFilters.tsx
Labels: bug

#2679 2363/Update email templates
  src/fides/api/ops/email_templates/templates/privacy_request_complete_access.html
  src/fides/api/ops/schemas/messaging/messaging.py
  src/fides/api/ops/service/messaging/message_dispatch_service.py
  src/fides/api/ops/service/privacy_request/request_runner_service.py
  tests/ops/service/privacy_request/request_runner_service_test.py
Labels: bug
