Repository ethyca/fides, pull requests merged in 2023-03, with the labels that each got.

#2677 2455/Configuration updates post-API
  clients/admin-ui/cypress/e2e/privacy-requests.cy.ts
  clients/admin-ui/cypress/fixtures/privacy-requests/messaging_configuration.json
  clients/admin-ui/cypress/support/stubs.ts
  clients/admin-ui/src/features/common/Layout.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/MailgunEmailConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/MessagingConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/S3StorageConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/StorageConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/TwilioEmailConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/TwilioSMS.tsx
  clients/admin-ui/src/features/privacy-requests/constants.ts
  clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts
  clients/admin-ui/src/features/privacy-requests/types.ts
  clients/admin-ui/src/pages/privacy-requests/configure.tsx
Labels: enhancement

#2727 2237/Test connection button
  clients/admin-ui/src/features/privacy-requests/configuration/MailgunEmailConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/TestMessagingProviderConnectionButton.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/TwilioEmailConfiguration.tsx
  clients/admin-ui/src/features/privacy-requests/configuration/TwilioSMS.tsx
  clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts
Labels: enhancement

#2655 Add Privacy Request Input Sanitization
  CHANGELOG.md
  noxfiles/dev_nox.py
  src/fides/api/custom_types.py
  src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py
  src/fides/api/ops/schemas/connection_configuration/connection_secrets_bigquery.py
  src/fides/api/ops/schemas/connection_configuration/connection_secrets_email.py
  src/fides/api/ops/schemas/drp_privacy_request.py
  src/fides/api/ops/schemas/messaging/messaging.py
  src/fides/api/ops/schemas/privacy_request.py
  src/fides/api/ops/schemas/redis_cache.py
  src/fides/api/ops/schemas/registration.py
  tests/lib/test_custom_types.py
  tests/ops/api/v1/endpoints/test_messaging_endpoints.py
  tests/ops/schemas/connection_configuration/test_connection_secrets_email.py
Labels: run unsafe ci checks

#2895 Fix Logo aspect ratio on Privacy Center `404` page and Consent Page
  CHANGELOG.md
  clients/privacy-center/pages/404.tsx
  clients/privacy-center/pages/consent.tsx
Labels: UI

#2750 Disabling traceback in logs
  .github/workflows/backend_checks.yml
  noxfiles/test_setup_nox.py
  tests/fixtures/saas/delighted_fixtures.py
  tests/fixtures/saas/yotpo_loyalty_fixtures.py
  tests/fixtures/saas/yotpo_reviews_fixtures.py
  tests/ops/integration_tests/limiter/test_rate_limiter.py
  tests/ops/integration_tests/saas/test_delighted_task.py
  tests/ops/integration_tests/saas/test_friendbuy_nextgen_task.py
  tests/ops/integration_tests/saas/test_yotpo_reviews_task.py
Labels: run unsafe ci checks

#2912 [#2911] Remove policy key from submission modal
  CHANGELOG.md
  clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestModal.tsx
  clients/privacy-center/components/modals/privacy-request-modal/RequestSubmitted.tsx
Labels: bug, UI, customer-request

#2935 Change placeholder email in privacy center
  CHANGELOG.md
  clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx
  clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx
Labels: UI
