Repository ethyca/fides, pull requests merged in 2023-01, with the labels that each got.

#1731 Populate Application DB instead of the Test DB
  .fides/db_dataset.yml
  .fides/fides.toml
  CHANGELOG.md
  docker-compose.yml
  docs/fides/docs/installation/configuration.md
  pyproject.toml
  src/fides/api/ctl/database/crud.py
  src/fides/api/ctl/database/database.py
  src/fides/api/ctl/database/seed.py
  src/fides/api/ctl/database/session.py
  src/fides/api/ctl/routes/crud.py
  src/fides/api/ctl/routes/datamap.py
  src/fides/api/ctl/routes/generate.py
  src/fides/api/ctl/routes/util.py
  src/fides/api/ctl/view.py
  src/fides/api/ops/common_exceptions.py
  src/fides/api/ops/service/connectors/fides/fides_client.py
  src/fides/api/ops/service/privacy_request/request_service.py
  src/fides/cli/utils.py
  src/fides/core/config/logging_settings.py
  src/fides/core/config/utils.py
  tests/ctl/api/test_seed.py
  tests/ctl/cli/test_cli_utils.py
  tests/ctl/conftest.py
  tests/ctl/database/test_crud.py
  tests/lib/conftest.py
  tests/ops/conftest.py
  tests/ops/fixtures/application_fixtures.py
  tests/ops/fixtures/fides_connector_example_fixtures.py
  tests/ops/service/connectors/fides/test_fides_client.py
  tests/ops/service/connectors/test_fides_connector.py
Labels: run unsafe ci checks

#2139 1800 - Update Privacy Center Icons
  CHANGELOG.md
  clients/privacy-center/components/Card.tsx
  clients/privacy-center/config/config.json
  clients/privacy-center/package-lock.json
  clients/privacy-center/pages/index.tsx
  clients/privacy-center/public/consent.svg
  clients/privacy-center/public/delete.svg
  clients/privacy-center/public/download.svg
  src/fides/data/sample_project/privacy_center/config/config.json
  src/fides/data/test_env/privacy_center_config/config.json
Labels: UI, Fides NUX Improvements

#2169 Dynamic imports for custom overrides and SaaS fixtures
  CHANGELOG.md
  src/fides/api/ops/service/saas_request/__init__.py
  src/fides/api/ops/service/saas_request/override_implementations/__init__.py
  tests/ops/conftest.py
  tests/ops/fixtures/saas/__init__.py
  tests/ops/fixtures/saas/firebase_auth_fixtures.py
  tests/ops/fixtures/saas/mailchimp_override_fixtures.py
  tests/ops/fixtures/saas/request_override/__init__.py
  tests/ops/fixtures/saas_example_fixtures.py
  tests/ops/integration_tests/saas/test_domo_task.py
  tests/ops/integration_tests/saas/test_rollbar_task.py
Labels: run unsafe ci checks

#2186 Importing custom request overrides in main.py
  CHANGELOG.md
  src/fides/api/main.py
Labels: run unsafe ci checks

#2171 Adding AuthenticatedClient to custom override interface
  CHANGELOG.md
  src/fides/api/ops/service/connectors/saas_connector.py
  src/fides/api/ops/service/saas_request/override_implementations/domo_request_overrides.py
  src/fides/api/ops/service/saas_request/override_implementations/firebase_auth_request_overrides.py
  src/fides/api/ops/service/saas_request/override_implementations/mailchimp_request_overrides.py
  src/fides/api/ops/service/saas_request/override_implementations/twilio_request_overrides.py
  src/fides/api/ops/service/saas_request/saas_request_override_factory.py
  tests/ops/integration_tests/saas/request_override/test_firebase_auth_task.py
  tests/ops/service/saas_request/test_saas_request_override_factory.py
Labels: run unsafe ci checks

#2199 1979/Blur after focus state on reprocess button
  clients/admin-ui/src/features/privacy-requests/RequestRow.tsx
  clients/admin-ui/src/features/privacy-requests/buttons/ReprocessButton.tsx
Labels: bug

#2194 Mailchimp Transactional Consent Connector [#2150]
  CHANGELOG.md
  data/saas/config/mailchimp_transactional_config.yml
  data/saas/dataset/mailchimp_transactional_dataset.yml
  data/saas/saas_connector_registry.toml
  src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py
  src/fides/api/ops/schemas/saas/saas_config.py
  src/fides/api/ops/schemas/saas/strategy_configuration.py
  src/fides/api/ops/service/authentication/authentication_strategy_api_key.py
  src/fides/api/ops/service/connectors/base_connector.py
  src/fides/api/ops/service/connectors/saas_connector.py
  src/fides/api/ops/service/privacy_request/request_runner_service.py
  tests/ops/fixtures/application_fixtures.py
  tests/ops/fixtures/saas/mailchimp_transactional_fixtures.py
  tests/ops/integration_tests/saas/test_mailchimp_transactional_task.py
  tests/ops/integration_tests/test_consent_request.py
  tests/ops/service/authentication/test_authentication_strategy_api_key.py
  tests/ops/service/connectors/test_saas_connector.py
  tests/ops/service/privacy_request/request_runner_service_test.py
Labels: run unsafe ci checks

#2225 [Unified Fides Resources] Update Test Env Setup and Quickstart
  .fides/fides.toml
  data/saas/dataset/recharge_dataset.yml
  scripts/quickstart.py
  scripts/setup/dataset.py
  tests/ops/fixtures/saas/friendbuy_nextgen_fixtures.py
  tests/ops/fixtures/saas/recharge_fixtures.py
Labels: run unsafe ci checks, Unified Fides Resources

#2251 2204/Swap modal button spots
  clients/admin-ui/src/features/common/WarningModal.tsx
Labels: bug

#2148 Add missing permission for user deletion in Admin UI
  CHANGELOG.md
  clients/admin-ui/src/constants.ts
  src/fides/lib/oauth/api/routes/user_endpoints.py
  tests/ops/api/v1/endpoints/test_user_endpoints.py
Labels: python, UI, javascript

#2198 Send pytest coverage reports to code climate
  .github/workflows/backend_checks.yml
  .gitignore
  CHANGELOG.md
  README.md
  noxfiles/ci_nox.py
  noxfiles/constants_nox.py
  noxfiles/run_infrastructure.py
  noxfiles/test_setup_nox.py
  pyproject.toml
  scripts/fix_coverage.py
Labels: run unsafe ci checks

#2277 2200 - Home screen header scaling and responsiveness issues
  CHANGELOG.md
  clients/admin-ui/src/home/HomeBanner.tsx
  clients/admin-ui/src/home/HomeLayout.tsx
Labels: UI, Fides NUX Improvements

#2315 Consent SaaS Config: Allow definition of multiple opt-in or opt-out requests
  data/saas/config/mailchimp_transactional_config.yml
  src/fides/api/ops/schemas/saas/saas_config.py
  src/fides/api/ops/service/connectors/saas_connector.py
  tests/ops/integration_tests/saas/test_mailchimp_transactional_task.py
  tests/ops/service/connectors/test_saas_connector.py
Labels: run unsafe ci checks

#2207 update firebase auth connector to support phone number identities
  data/saas/config/firebase_auth_config.yml
  src/fides/api/ops/service/connectors/saas_query_config.py
  src/fides/api/ops/service/saas_request/override_implementations/firebase_auth_request_overrides.py
  src/fides/api/ops/util/saas_util.py
  tests/ops/fixtures/saas/firebase_auth_fixtures.py
  tests/ops/integration_tests/saas/request_override/test_firebase_auth_task.py
Labels: do not merge

#2360 Reduce size of local Docker images by fixing `.dockerignore` patterns
  .dockerignore
  CHANGELOG.md
  Dockerfile
Labels: run unsafe ci checks

#2384 Skip Missing Param Values
  data/saas/config/google_analytics_config.yml
  src/fides/api/ops/schemas/saas/saas_config.py
  src/fides/api/ops/service/connectors/saas_connector.py
  src/fides/api/ops/service/connectors/saas_query_config.py
  tests/ops/integration_tests/saas/test_google_analytics_task.py
  tests/ops/integration_tests/saas/test_mailchimp_transactional_task.py
  tests/ops/service/connectors/test_saas_connector.py
  tests/ops/service/connectors/test_saas_queryconfig.py
Labels: run unsafe ci checks
